version: 2.1

orbs:
  telegram: jcminarro/telegram@dev:alpha

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - telegram/notify:
          message: "Hello Orb!!!"
      - run:
          name: Create a file
          command: echo "Hello Orb!!!" > orbFile.txt
      - telegram/sendfile:
          file-path: orbFile.txt